//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenio
    {
        public int IDKorisnik { get; set; }
        public int IDOdgovor { get; set; }
        public string Ocena { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Odgovor Odgovor { get; set; }
    }
}
