//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odgovor()
        {
            this.Ocenio = new HashSet<Ocenio>();
            this.Odgovor1 = new HashSet<Odgovor>();
        }
    
        public int IDOdgovor { get; set; }
        public Nullable<int> Odgovoreni { get; set; }
        public string Tekst { get; set; }
        public int IDKorisnik { get; set; }
        public int BrojPozitivnihOcena { get; set; }
        public int BrojNegativnihOcena { get; set; }
        public System.DateTime DatumPravljenja { get; set; }
        public string KorenoPitanje { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocenio> Ocenio { get; set; }
        public virtual Pitanje Pitanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovor1 { get; set; }
        public virtual Odgovor Odgovor2 { get; set; }
    }
}
