//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pitanje()
        {
            this.Odgovor = new HashSet<Odgovor>();
        }
    
        public string Tekst { get; set; }
        public byte[] Slika { get; set; }
        public Nullable<int> IDKategorija { get; set; }
        public int Autor { get; set; }
        public System.DateTime DatumPravljenja { get; set; }
        public Nullable<System.DateTime> DatumZakljucavanja { get; set; }
        public string Naslov { get; set; }
        public string Status { get; set; }
        public string EkstenzijaSlike { get; set; }
        public string IDKanal { get; set; }
        public string IDPitanje { get; set; }
    
        public virtual Kanal Kanal { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovor { get; set; }
    }
}
