//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrednosti
    {
        public string Naziv { get; set; }
        public Nullable<int> Cena { get; set; }
        public Nullable<int> BrojTokena { get; set; }
    }
}
